# Generated by Django 3.1.2 on 2020-12-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamNames', models.CharField(max_length=500)),
                ('predictions', models.CharField(max_length=500)),
            ],
        ),
    ]
