# Generated by Django 3.0.8 on 2020-12-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamDict',
        ),
    ]
